---
- name: Install OpenJDK 17 for Jenkins
  apt:
    name: openjdk-17-jdk
    state: present

- name: Add Jenkins official repository key
  apt_key:
    url: https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
    state: present

- name: Add Jenkins repository
  apt_repository:
    repo: "deb https://pkg.jenkins.io/debian-stable binary/"
    state: present

- name: Install Jenkins LTS
  apt:
    name: jenkins
    state: present
    update_cache: yes

- name: Ensure Jenkins service is running
  systemd:
    name: jenkins
    state: started
    enabled: yes

- name: Add jenkins user to docker group
  user:
    name: jenkins
    groups: docker
    append: yes
